### ISSUE TITLE
MongoDB와 연동으로 인해 채팅 메세지 받을 때 병목 발생

### ISSUE THREAD

**Issue by papari1123** [boostcampaitech4lv23nlp2/final-project-level3-nlp-08#4]
친 메세지를 받아오는 chat 함수에서 

아래 176, 177번 MongoDB와 연동하면서 생기는 병목이 발생함.

이 때문에 채팅을 약 0.5초 이내로 빨리 칠 경우 채팅이 먹히거나, 딜레이가 생김

https://github.com/boostcampaitech4lv23nlp2/final-project-level3-nlp-08/blob/ee6c84a7c9c3821dc9a4b2a03c3d9c7bd7fb3a85/app.py#L176-L178

- 이 이슈는 프로토타입 수준에서는 크게 문제 되지는 않음.
- 다만 수정 방법은 있음.
   - MongoDB 연동 부분을 블로킹 없이 비동기로 처리 (조금어려울 수 있음0
   - 채팅을 mongoDB에 보내지말고, 로컬에 가지고 있기 (전역 변수 또는 전역 인스턴스 활용, 쉬움)

**Comment by siryuon** [comment]
채팅을 로컬에 가지고 있는거는, 이전 버전 마냥 될 것 같아서 안될 것 같고, global 변수로도 해결이 안될 것 같은데, 방법이 있을까?

**Comment by papari1123** [comment]
병목이라고 생각한 부분 직접 측정을 해봤는데, 생각보다 짧게 걸려서,
다른 곳에서 문제가 있을 것으로 판단하고, 일단 이 이슈는 close합니다.
db insert time : 6263427734375
```
await stack_message(data, collection) # 7.07 msec
await get_messages() # 3.22 msec
```
